import Head from 'next/head';
import React from 'react';
import Link from 'next/link';
import styles from '../styles/About.module.css';

const About = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Class 9 Guide</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h2 className={styles.h2}>Hello this is a guide an Class 9 and u can join our discord server in our home page for more info.
        This website will help you in studies in some fun ways. Use this website to continously monitor your progress in studies with a wide variety of quizes for all subjects.

      </h2>
    </div>

  )
};

export default About;