import Head from 'next/head';
//import Image from 'next/image';//
//import Script from 'next/script';//
// import Link from 'next/link';
import styles from '../styles/Home.module.css';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Class 9 Guide</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          <span className='mySpan'>Welcome To Class 9 Guide!</span>

        </h1>
        <div className={styles.imageWrap}>
          {/* <img className={styles.myImg} src='/Backgroud.avif' width={200} height={200}/> */}
          <img className={styles.myImg} src="/Kensri.jpg" width={300} height={150} alt="vibe blog"/>
        </div>

        <div>
          <h2 className={styles.h2}>
          <iframe src="https://discord.com/widget?id=941249480701919242&theme=light" width="1000" height="200"></iframe>
          </h2>
          <div>
            <h3 className={styles.h3}>Here are the subjects.</h3>
            <p>Click on this button for more detailed informtion!</p>
            <button className={styles.btn} onClick={event => window.location.href = `/blog`}>Read More</button>
          </div>
        </div>
      </main>
    </div>
  )
}
